"""Builds the stored half of the saints data: which Wikidata entity each calendar saint is, and which
Wikidata entity each country is.

    python scripts/saints/build_saints.py     # from the realm root

calendar-saints.json is the reviewed mapping from romcal's martyrology ids to Wikidata QIDs —
generated by match_calendar_saints.py (Wikidata's entity search, accepting only a human with a
canonization status or feast day) and then corrected by hand where the search returned a church, a
painting or a namesake. `matched` says which. Countries come from Wikidata's ISO 3166-1 alpha-2
codes (P297), fetched once and cached under data/source/.
"""
import json, os, time, urllib.parse, urllib.request
import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
HERE = os.path.dirname(os.path.abspath(__file__))
CACHE = os.path.join(ROOT, 'data', 'source', 'wikidata')
REF = os.path.join(ROOT, 'reference')
UA = {'User-Agent': 'realm-bible-build/0.1 (https://github.com/embabel-worlds/realm-bible)'}
WD = 'http://www.wikidata.org/entity/'


class Quoted(str):
    pass


yaml.add_representer(Quoted, lambda d, v: d.represent_scalar('tag:yaml.org,2002:str', v, style='"'))
q = lambda v: Quoted(v) if isinstance(v, str) else ({k: q(x) for k, x in v.items()} if isinstance(v, dict) else ([q(x) for x in v] if isinstance(v, list) else v))


def sparql(name, query):
    """One query, cached by name; backs off on 429/503 and honours Retry-After."""
    path = os.path.join(CACHE, name + '.json')
    if os.path.exists(path):
        return json.load(open(path))
    os.makedirs(CACHE, exist_ok=True)
    url = 'https://query.wikidata.org/sparql?' + urllib.parse.urlencode({'query': query, 'format': 'json'})
    for attempt in range(6):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
                data = json.load(r)['results']['bindings']
            json.dump(data, open(path, 'w'))
            return data
        except urllib.error.HTTPError as e:
            wait = int(e.headers.get('Retry-After') or 2 ** attempt)
        except Exception:
            wait = 2 ** attempt
        time.sleep(wait)
    raise RuntimeError(f'{name}: Wikidata did not answer')


def write(name, header, records):
    with open(os.path.join(REF, name), 'w') as f:
        f.write(header.rstrip() + '\n\n')
        yaml.dump(q(records), f, allow_unicode=True, sort_keys=False, width=10_000)


saints = json.load(open(os.path.join(HERE, 'calendar-saints.json')))
write('catholic-saints.yml', """
# Which Wikidata entity each saint of the General Roman Calendar is (romcal martyrology id -> QID), for
# fetching the saint's card live. Matched by Wikidata's entity search and corrected by hand where the
# search returned a church, a painting or a namesake (`matched: curated`). Feasts of Our Lady, of John
# the Baptist and of Peter and Paul point at the person they honour. Generated by
# scripts/saints/build_saints.py from scripts/saints/calendar-saints.json.
""", [{'type': 'CalendarSaint', 'data': {'saintId': s['saintId'], 'qid': s['qid'], 'wd': WD + s['qid'],
                                          'label': s['label'], 'matched': s['matched'], 'canonization': s['canonization'].lower()}}
      for s in saints])

bridge = json.load(open(os.path.join(HERE, 'scripture-saints.json')))
write('catholic-scripture-saints.yml', """
# Saints who are also people of Scripture: a Wikidata saint and the Theographic person who is them, hand
# matched (scripts/saints/scripture-saints.json) — names alone would confuse the five Marys and the two
# Jameses. Joachim, Anne and Raphael are honoured in the calendar but not named in the 66 books, so they
# have no entry. Generated by scripts/saints/build_saints.py.
""", [{'type': 'ScriptureSaint', 'data': {'qid': b['qid'], 'wd': WD + b['qid'], 'personLookup': b['personLookup'], 'label': b['label']}}
      for b in bridge])

rows = sparql('countries-iso2', """
SELECT ?c ?iso (SAMPLE(?l) AS ?name) WHERE {
  ?c wdt:P297 ?iso ; wdt:P31/wdt:P279* wd:Q6256 .
  ?c rdfs:label ?l FILTER(LANG(?l) = "en")
} GROUP BY ?c ?iso
""")
by_iso = {}
for r in rows:
    iso = r['iso']['value'].upper()
    by_iso.setdefault(iso, (r['c']['value'], r['name']['value']))
write('catholic-countries.yml', """
# ISO 3166-1 alpha-2 codes to Wikidata country entities (P297), so the app can start from the reader's
# locale. Wikidata, CC0. Generated by scripts/saints/build_saints.py.
""", [{'type': 'Country', 'data': {'iso2': iso, 'wd': wd, 'qid': wd.rsplit('/', 1)[1], 'name': name}}
      for iso, (wd, name) in sorted(by_iso.items())])
print(len(saints), 'calendar saints;', len(bridge), 'scripture saints;', len(by_iso), 'countries')
