"""
Build the realm's reference data from its published sources.

The stored graph is Book → Passage → Verse, and every verse carries two texts: the King James
Version (the default) and the World English Bible (the modern choice). Both are stored, not
fetched, because both must be SEARCHABLE — "passages that mention a goat" is a scan over text, and
a scan cannot be answered by a producer that fetches one verse per call. The five older
translations are the other way round: fetched on demand, one verse at a time, never searched.

Sources, all downloaded into data/source/ on first run:
  Theographic Bible Metadata (CC BY-SA 4.0) — Books.csv, Chapters.csv, Verses.csv. The KJV text,
      the chapter and book structure, and each verse's `people`: the Theographic person ids it
      mentions. Those ids are what the BiblePerson producer joins on.
  eBible.org WEB, verse-per-line (public domain) — keyed by USFM book code (`JDG 3:21`).

A Passage is a CHAPTER. Pericope boundaries are an editorial choice that differs between
publishers; chapters are the one division every source here shares.

Run from the realm root:  python scripts/build_reference.py
"""

import csv
import io
import re
import sys
import urllib.request
import zipfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "source"
REFERENCE = ROOT / "reference"

THEOGRAPHIC = "https://raw.githubusercontent.com/robertrouse/theographic-bible-metadata/master/CSV/{}.csv"
WEB_VPL = "https://ebible.org/Scriptures/engwebp_vpl.zip"


def fetch() -> None:
    SOURCE.mkdir(parents=True, exist_ok=True)
    for name in ("Books", "Chapters", "Verses", "People"):
        path = SOURCE / f"{name}.csv"
        if not path.exists():
            print(f"downloading {name}.csv")
            urllib.request.urlretrieve(THEOGRAPHIC.format(name), path)
    web = SOURCE / "engwebp_vpl.txt"
    if not web.exists():
        print("downloading WEB")
        with urllib.request.urlopen(WEB_VPL) as response:
            web.write_bytes(zipfile.ZipFile(io.BytesIO(response.read())).read("engwebp_vpl.txt"))


def rows(name: str) -> list[dict]:
    with open(SOURCE / f"{name}.csv", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def web_text(books: list[dict]) -> dict[str, str]:
    """WEB verses keyed by OSIS. USFM codes are mapped by canonical ORDER, which both sources share."""
    usfm_order: list[str] = []
    by_usfm: dict[tuple[str, int, int], str] = {}
    for line in (SOURCE / "engwebp_vpl.txt").read_text(encoding="utf-8").splitlines():
        m = re.match(r"^(\w{3}) (\d+):(\d+) (.*)$", line)
        if not m:
            continue
        code, chapter, verse, text = m.group(1), int(m.group(2)), int(m.group(3)), m.group(4).strip()
        if code not in usfm_order:
            usfm_order.append(code)
        by_usfm[(code, chapter, verse)] = text
    if len(usfm_order) != len(books):
        sys.exit(f"WEB has {len(usfm_order)} books, Theographic {len(books)}: refusing to guess the mapping")
    osis_of = {code: b["osisName"] for code, b in zip(usfm_order, sorted(books, key=lambda b: int(b["bookOrder"])))}
    return {f"{osis_of[c]}.{ch}.{v}": t for (c, ch, v), t in by_usfm.items()}


def split(value: str) -> list[str]:
    return [v for v in (value or "").split(",") if v]


def write(filename: str, header: str, records: list[dict]) -> None:
    body = yaml.safe_dump(records, allow_unicode=True, sort_keys=False, width=10_000)
    (REFERENCE / filename).write_text(header.strip() + "\n\n" + body, encoding="utf-8")
    print(f"{filename}: {len(records)} record(s)")


def main() -> None:
    fetch()
    REFERENCE.mkdir(exist_ok=True)
    books = rows("Books")
    book_name = {b["osisName"]: b["bookName"] for b in books}
    web = web_text(books)

    write("bible-01-books.yml", """
# The 66 books, in canonical order. Generated by scripts/build_reference.py from Theographic
# Bible Metadata (CC BY-SA 4.0) — do not edit by hand.
""", [
        {"type": "Book", "data": {
            "osis": b["osisName"], "name": b["bookName"], "bookOrder": int(b["bookOrder"]),
            "testament": b["testament"], "division": b["bookDiv"],
        }}
        for b in sorted(books, key=lambda b: int(b["bookOrder"]))
    ])

    write("bible-02-passages.yml", """
# One Passage per chapter. Generated by scripts/build_reference.py from Theographic Bible Metadata
# (CC BY-SA 4.0) — do not edit by hand.
""", [
        {"type": "Passage",
         "data": {"osis": c["osisRef"], "name": f"{book_name[c['book']]} {c['chapterNum']}",
                  "book": c["book"], "chapter": int(c["chapterNum"]), "verseCount": len(split(c["verses"]))},
         "relations": [{"predicate": "IN", "to": {"type": "Book", "osis": c["book"]}}]}
        for c in rows("Chapters")
    ])

    verses = rows("Verses")
    missing_web = [v["osisRef"] for v in verses if v["osisRef"] not in web]
    records: dict[str, list[dict]] = {b["osisName"]: [] for b in books}
    for v in verses:
        chapter = int(v["chapter"].split(".")[-1])
        data = {
            "osis": v["osisRef"],
            "name": f"{book_name[v['book']]} {chapter}:{v['verseNum']}",
            # The key the translation producers fetch by. bible-api reads `SongofSolomon2:9` as
            # `Song of Solomon 2:9`, and the engine will not put a key containing whitespace into a
            # URL path segment, so the human reference cannot be the key itself.
            "apiRef": f"{book_name[v['book']]}{chapter}:{v['verseNum']}".replace(" ", ""),
            "book": v["book"], "chapter": chapter, "verse": int(v["verseNum"]),
            "text": v["verseText"].strip(),
            "web": web.get(v["osisRef"]),
            "people": split(v["people"]),
        }
        if v["event"]:
            data["event"] = v["event"]
        records[v["book"]].append({
            "type": "Verse", "data": {k: val for k, val in data.items() if val not in (None, [])},
            "relations": [{"predicate": "IN", "to": {"type": "Passage", "osis": v["chapter"]}}]})
    # ONE FILE PER BOOK. The host's YAML reader refuses a document over 3 MB, and all 31,102 verses
    # in one file come to ~16 MB. Psalms, the largest book, is ~1.2 MB. The names sort after the
    # passages file, which matters: a verse's IN relation needs its Passage to exist already.
    for stale in REFERENCE.glob("bible-03-verses*.yml"):
        stale.unlink()
    for b in sorted(books, key=lambda b: int(b["bookOrder"])):
        write(f"bible-03-verses-{int(b['bookOrder']):02d}-{b['osisName']}.yml", f"""
# Every verse of {b['bookName']}, with the King James text (`text`, the default) and the World
# English Bible (`web`, the modern choice), and the Theographic ids of the people each mentions.
# Generated by scripts/build_reference.py from Theographic Bible Metadata (CC BY-SA 4.0) and
# eBible.org's WEB (public domain) — do not edit by hand.
""", records[b["osisName"]])
    if missing_web:
        # Versification differs between editions; a verse with no WEB counterpart keeps its KJV text
        # and simply has no `web`, rather than borrowing a neighbour's.
        print(f"{len(missing_web)} verse(s) have no WEB counterpart: {missing_web[:10]}")


if __name__ == "__main__":
    main()
