/*
 * Writes reference/catholic-calendar-<year>.yml: the General Roman Calendar for each year in
 * [FIRST, LAST], computed by romcal (MIT, https://github.com/romcal/romcal), pinned in package.json.
 *
 * A calendar is computed, not fetched: Easter moves, a Sunday outranks most saints, and a solemnity
 * falling on a Sunday of Advent is transferred. romcal implements the General Norms for the
 * Liturgical Year (1969), so the stored day is the day a parish celebrates under the universal
 * calendar. National and diocesan calendars differ (a country's patron, transferred holy days of
 * obligation); this file is the universal one, and says so.
 *
 * One LiturgicalDay per date, and one Celebration per thing celebrated that day — a weekday with
 * two optional memorials has three. `saints` on a Celebration lists romcal's martyrology ids, which
 * scripts/saints/ maps to Wikidata. The calendar's id is stored as `celebrationId`: a property named
 * `id` would collide with the node's own identifier in the graph store.
 *
 *   npm ci && node build.mjs
 */
import { Romcal } from 'romcal';
import { GeneralRoman_En } from '@romcal/calendar.general-roman';
import { stringify } from 'yaml';
import { writeFileSync } from 'node:fs';

const FIRST = 2025, LAST = 2030;
const RANK_ORDER = { SOLEMNITY: 1, SUNDAY: 2, FEAST: 3, MEMORIAL: 4, OPTIONAL_MEMORIAL: 5, WEEKDAY: 6 };
/* romcal names both apostles James `james_apostle`: James the Greater (25 July) and James the Less, kept
 * with Philip on 3 May. They are two people with two Wikidata entities, so the May one is renamed. */
const saintId = (celebrationId, id) =>
  celebrationId === 'philip_and_james_apostles' && id === 'james_apostle' ? 'james_the_less_apostle' : id;
const words = (s) => (s || '').toLowerCase().replace(/_/g, ' ');

const romcal = new Romcal({ localizedCalendar: GeneralRoman_En, scope: 'gregorian' });
for (let year = FIRST; year <= LAST; year++) {
  const calendar = await romcal.generateCalendar(year);
  const records = [];
  for (const [date, items] of Object.entries(calendar)) {
    const principal = items[0];
    records.push({
      type: 'LiturgicalDay',
      data: {
        date,
        weekday: new Date(date + 'T12:00:00Z').toLocaleDateString('en-GB', { weekday: 'long', timeZone: 'UTC' }),
        celebration: principal.name,
        rank: words(principal.rank),
        colour: words(principal.colors?.[0]),
        season: words(principal.seasons?.[0]),
        sundayCycle: words(principal.cycles?.sundayCycle).replace('year ', ''),
        weekdayCycle: words(principal.cycles?.weekdayCycle).replace('year ', ''),
        psalterWeek: words(principal.cycles?.psalterWeek).replace('week ', ''),
        holyDayOfObligation: items.some((x) => x.isHolyDayOfObligation),
      },
    });
    items.forEach((x, i) => records.push({
      type: 'Celebration',
      data: {
        key: `${date}/${x.id}`,
        celebrationId: x.id,
        date,
        name: x.name,
        rank: words(x.rank),
        rankOrder: RANK_ORDER[x.rank] ?? 9,
        principal: i === 0,
        optional: Boolean(x.isOptional),
        colours: (x.colors || []).map(words),
        holyDayOfObligation: Boolean(x.isHolyDayOfObligation),
        saints: (x.martyrology || []).map((m) => saintId(x.id, m.id)),
      },
      relations: [{ predicate: 'ON', to: { type: 'LiturgicalDay', date } }],
    }));
  }
  const header = `# The General Roman Calendar for ${year}, computed by romcal 3.0.0-dev.140 (MIT,
# https://github.com/romcal/romcal). Generated by scripts/calendar/build.mjs — do not edit by hand.
# The universal calendar only: national and diocesan calendars, and holy days transferred by a
# bishops' conference, are not applied.
`;
  writeFileSync(`../../reference/catholic-calendar-${year}.yml`, header + '\n' + stringify(records, { lineWidth: 0, defaultStringType: 'QUOTE_DOUBLE', defaultKeyType: 'PLAIN' }));
  console.log(year, Object.keys(calendar).length, 'days,', records.length - Object.keys(calendar).length, 'celebrations');
}
